[taskbook]
taskbookDirectory = "/Users/xavier/.config/taskbook"
displayCompleteTasks = true
displayProgressOverview = true
displayWarnings = true
enableCopyID = false
defaultBoard = "backlog"
editor = "nvim"
suspiciousDuration = 3
defaultContext = "qa"
tshirtSizes = true
plannedHoursWarn = 6
plannedHoursError = 8
greetings = true
doneLast = true

[plugin.goals]
board = "goal"

[plugin.calendar]
board = "calendar"
gc = true

[plugin.srr]
prefix = "deck"
tag = "srr"

[alias]
goto = "tb print --format json $argv | jq --raw-output '.link' | xargs open"
dojo = "clear && tb list must should would calendar"
later = "tb move @stash $argv"
block = "tb move @blocked $argv"
pretty = "tb print $argv | glow"
